apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0bxd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0bxd
    app.kubernetes.io/part-of: ci1t-830-0020-app
  name: devfile-sample-0bxd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-0bxd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-0bxd
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0020-tenant/ci1t-830-0020-app/devfile-sample-0bxd@sha256:404898aab941ddb0e9ab6f96b245f84b4a842860fb185063f47a57dbe1be68f4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
